/**
 * Snippet Data Module - Radiology Report Snippets
 * Part of RadReport AI Data Layer
 * Contains 1420+ complete snippet objects
 */

/**
 * Snippet categories
 */
const SNIPPET_CATEGORIES = [
  'FINDING', 'IMPRESSION', 'TECHNIQUE', 'NORMAL', 'PATHOLOGY',
  'MEASUREMENT', 'COMPARISON', 'ADDENDUM', 'FOLLOWUP', 'MODIFIER',
  'ANATOMY', 'HISTORY', 'CONCLUSION', 'RECOMMENDATION', 'QUALITY',
  'ARTIFACT', 'LIMITATION', 'VARIANT', 'COMPLICATION', 'PROCEDURE',
  'DOSE', 'CONTRAST', 'POSITIONING', 'TIMING', 'STATISTICS'
];

/**
 * Gets complete snippet data
 * @returns {Array} Array of snippet objects
 */
export function getSnippetData() {
  return [
    // ============ ANATOMY SNIPPETS - HEAD ============
    {
      id: 'snip_anat_head_001',
      trigger: '/frontal',
      expansion: 'Frontal lobe demonstrates normal gray-white matter differentiation. No focal lesions, mass effect, or abnormal signal.',
      name: 'Frontal Lobe Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['frontal', 'lobe', 'normal', 'brain'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN', 'FRONTAL'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_head_002',
      trigger: '/temporal',
      expansion: 'Temporal lobe demonstrates normal gray-white matter differentiation. No focal lesions, mass effect, or abnormal signal. Hippocampi are normal in size and signal.',
      name: 'Temporal Lobe Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['temporal', 'lobe', 'hippocampus', 'normal', 'brain'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN', 'TEMPORAL'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_head_003',
      trigger: '/parietal',
      expansion: 'Parietal lobe demonstrates normal gray-white matter differentiation. No focal lesions, mass effect, or abnormal signal.',
      name: 'Parietal Lobe Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['parietal', 'lobe', 'normal', 'brain'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN', 'PARIETAL'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_head_004',
      trigger: '/occipital',
      expansion: 'Occipital lobe demonstrates normal gray-white matter differentiation. No focal lesions or abnormal signal. Visual cortex is intact.',
      name: 'Occipital Lobe Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['occipital', 'lobe', 'normal', 'brain', 'visual'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN', 'OCCIPITAL'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_head_005',
      trigger: '/cerebellum',
      expansion: 'Cerebellum is normal in size and configuration. Cerebellar hemispheres demonstrate normal folial pattern. No masses or abnormal signal.',
      name: 'Cerebellum Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['cerebellum', 'normal', 'posterior fossa'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'CEREBELLUM'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_head_006',
      trigger: '/brainstem',
      expansion: 'Brainstem is normal in size and contour. No abnormal signal or enhancement. Cranial nerve nuclei are unremarkable.',
      name: 'Brainstem Normal',
      category: 'ANATOMY',
      subcategory: 'Brain',
      keywords: ['brainstem', 'midbrain', 'pons', 'medulla', 'normal'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAINSTEM'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ ANATOMY SNIPPETS - CHEST ============
    {
      id: 'snip_anat_chest_001',
      trigger: '/lung_r',
      expansion: 'Right lung is clear. No focal consolidation, nodules, masses, or pleural effusions. Bronchi are patent.',
      name: 'Right Lung Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['right', 'lung', 'clear', 'normal'],
      variables: [],
      modalityTags: ['CT', 'X-RAY', 'MRI'],
      anatomyTags: ['CHEST', 'RIGHT LUNG'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_chest_002',
      trigger: '/lung_l',
      expansion: 'Left lung is clear. No focal consolidation, nodules, masses, or pleural effusions. Bronchi are patent.',
      name: 'Left Lung Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['left', 'lung', 'clear', 'normal'],
      variables: [],
      modalityTags: ['CT', 'X-RAY', 'MRI'],
      anatomyTags: ['CHEST', 'LEFT LUNG'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_chest_003',
      trigger: '/heart_normal',
      expansion: 'Heart is normal in size. Cardiac chambers are not enlarged. No pericardial effusion. Cardiac silhouette is within normal limits.',
      name: 'Heart Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['heart', 'cardiac', 'normal', 'size'],
      variables: [],
      modalityTags: ['CT', 'X-RAY', 'MRI'],
      anatomyTags: ['CHEST', 'HEART'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_chest_004',
      trigger: '/mediastinum',
      expansion: 'Mediastinal contours are normal. No lymphadenopathy or masses. Prevascular space is clear.',
      name: 'Mediastinum Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['mediastinum', 'normal', 'lymph nodes'],
      variables: [],
      modalityTags: ['CT', 'X-RAY', 'MRI'],
      anatomyTags: ['CHEST', 'MEDIASTINUM'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_chest_005',
      trigger: '/hila',
      expansion: 'Hilar structures are normal in size and configuration. No masses or lymphadenopathy. Pulmonary arteries are patent.',
      name: 'Hila Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['hila', 'hilum', 'normal', 'pulmonary artery'],
      variables: [],
      modalityTags: ['CT', 'X-RAY', 'MRI'],
      anatomyTags: ['CHEST', 'HILA'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_chest_006',
      trigger: '/pleura',
      expansion: 'Pleural surfaces are smooth. No pleural effusions, thickening, or pneumothorax.',
      name: 'Pleura Normal',
      category: 'ANATOMY',
      subcategory: 'Chest',
      keywords: ['pleura', 'normal', 'effusion', 'thickening'],
      variables: [],
      modalityTags: ['CT', 'X-RAY'],
      anatomyTags: ['CHEST', 'PLEURA'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ ANATOMY SNIPPETS - ABDOMEN ============
    {
      id: 'snip_anat_abdo_001',
      trigger: '/liver',
      expansion: 'Liver is normal in size and echotexture. No focal lesions, masses, or biliary ductal dilatation. Hepatic veins are patent.',
      name: 'Liver Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['liver', 'normal', 'hepatic', 'size'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'LIVER'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_002',
      trigger: '/gallbladder',
      expansion: 'Gallbladder is normal in size and wall thickness. No stones, sludge, or pericholecystic fluid. Gallbladder empties well.',
      name: 'Gallbladder Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['gallbladder', 'gb', 'normal', 'stones'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'GALLBLADDER'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_003',
      trigger: '/pancreas',
      expansion: 'Pancreas is normal in size and contour. No masses, calcifications, or pancreatic duct dilatation. Pancreatic head, body, and tail are unremarkable.',
      name: 'Pancreas Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['pancreas', 'normal', 'pancreatic'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'PANCREAS'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_004',
      trigger: '/spleen',
      expansion: 'Spleen is normal in size and echotexture. No focal lesions, infarctions, or masses.',
      name: 'Spleen Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['spleen', 'splenic', 'normal', 'size'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'SPLEEN'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_005',
      trigger: '/kidney_r',
      expansion: 'Right kidney is normal in size and contour. No hydronephrosis, stones, or masses. Corticomedullary differentiation is preserved.',
      name: 'Right Kidney Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['right', 'kidney', 'renal', 'normal'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'RIGHT KIDNEY'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_006',
      trigger: '/kidney_l',
      expansion: 'Left kidney is normal in size and contour. No hydronephrosis, stones, or masses. Corticomedullary differentiation is preserved.',
      name: 'Left Kidney Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['left', 'kidney', 'renal', 'normal'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND'],
      anatomyTags: ['ABDOMEN', 'LEFT KIDNEY'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_abdo_007',
      trigger: '/adrenal',
      expansion: 'Both adrenal glands are normal in size and morphology. No masses or thickening.',
      name: 'Adrenal Glands Normal',
      category: 'ANATOMY',
      subcategory: 'Abdomen',
      keywords: ['adrenal', 'gland', 'normal', 'suprarenal'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['ABDOMEN', 'ADRENAL'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ ANATOMY SNIPPETS - SPINE ============
    {
      id: 'snip_anat_spine_001',
      trigger: '/cord',
      expansion: 'Spinal cord demonstrates normal signal intensity. No cord edema, hemorrhage, or masses. No cord compression.',
      name: 'Spinal Cord Normal',
      category: 'ANATOMY',
      subcategory: 'Spine',
      keywords: ['spinal cord', 'cord', 'normal', 'signal'],
      variables: [],
      modalityTags: ['MRI', 'CT'],
      anatomyTags: ['SPINE', 'SPINAL CORD'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_spine_002',
      trigger: '/disc_normal',
      expansion: 'Intervertebral discs demonstrate normal hydration and height. No disc protrusions, extrusions, or bulges.',
      name: 'Intervertebral Disc Normal',
      category: 'ANATOMY',
      subcategory: 'Spine',
      keywords: ['disc', 'intervertebral', 'normal', 'height'],
      variables: [],
      modalityTags: ['MRI', 'CT', 'X-RAY'],
      anatomyTags: ['SPINE', 'DISC'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_anat_spine_003',
      trigger: '/conus',
      expansion: 'Conus medullaris terminates at the L1-L2 level, which is normal. No cord edema or masses.',
      name: 'Conus Medullaris Normal',
      category: 'ANATOMY',
      subcategory: 'Spine',
      keywords: ['conus', 'medullaris', 'normal', 'level'],
      variables: [],
      modalityTags: ['MRI'],
      anatomyTags: ['SPINE', 'CONUS'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ TECHNIQUE SNIPPETS ============
    {
      id: 'snip_tech_001',
      trigger: '/ct_wo',
      expansion: 'Axial CT images were obtained without intravenous contrast.',
      name: 'CT Without Contrast',
      category: 'TECHNIQUE',
      subcategory: 'CT',
      keywords: ['ct', 'without', 'contrast', 'non-contrast'],
      variables: [],
      modalityTags: ['CT'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_tech_002',
      trigger: '/ct_w',
      expansion: 'Axial CT images were obtained with intravenous contrast. Coronal and sagittal reconstructions were generated.',
      name: 'CT With Contrast',
      category: 'TECHNIQUE',
      subcategory: 'CT',
      keywords: ['ct', 'with', 'contrast', 'iv contrast'],
      variables: [],
      modalityTags: ['CT'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_tech_003',
      trigger: '/mri_wo',
      expansion: 'MRI was performed without intravenous contrast. Sequences include T1-weighted, T2-weighted, FLAIR, and diffusion-weighted imaging.',
      name: 'MRI Without Contrast',
      category: 'TECHNIQUE',
      subcategory: 'MRI',
      keywords: ['mri', 'without', 'contrast', 't1', 't2', 'flair'],
      variables: [],
      modalityTags: ['MRI'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_tech_004',
      trigger: '/mri_w',
      expansion: 'MRI was performed with and without intravenous contrast. Sequences include T1-weighted, T2-weighted, FLAIR, diffusion-weighted, susceptibility-weighted, and post-contrast T1-weighted imaging.',
      name: 'MRI With Contrast',
      category: 'TECHNIQUE',
      subcategory: 'MRI',
      keywords: ['mri', 'with', 'contrast', 'gadolinium', 'post-contrast'],
      variables: [],
      modalityTags: ['MRI'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_tech_005',
      trigger: '/us_doppler',
      expansion: 'Gray scale and color Doppler ultrasound was performed.',
      name: 'Ultrasound with Doppler',
      category: 'TECHNIQUE',
      subcategory: 'Ultrasound',
      keywords: ['ultrasound', 'doppler', 'color doppler', 'vascular'],
      variables: [],
      modalityTags: ['ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_tech_006',
      trigger: '/xray_pa_lat',
      expansion: 'PA and lateral views of the ___ were obtained.',
      name: 'X-Ray PA and Lateral',
      category: 'TECHNIQUE',
      subcategory: 'X-RAY',
      keywords: ['x-ray', 'radiograph', 'pa', 'lateral', 'views'],
      variables: ['body part'],
      modalityTags: ['X-RAY'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ FINDING SNIPPETS ============
    {
      id: 'snip_find_001',
      trigger: '/no_acute',
      expansion: 'No acute intracranial abnormality is identified.',
      name: 'No Acute Intracranial Abnormality',
      category: 'FINDING',
      subcategory: 'Brain',
      keywords: ['no acute', 'normal', 'intracranial', 'negative'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: true,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_002',
      trigger: '/no_mass',
      expansion: 'No mass, mass effect, or midline shift is identified.',
      name: 'No Mass or Mass Effect',
      category: 'FINDING',
      subcategory: 'Brain',
      keywords: ['mass', 'mass effect', 'midline shift', 'negative'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_003',
      trigger: '/no_hemorrhage',
      expansion: 'No intracranial hemorrhage, extraaxial collection, or hyperdensity is identified.',
      name: 'No Hemorrhage',
      category: 'FINDING',
      subcategory: 'Brain',
      keywords: ['hemorrhage', 'bleed', 'hematoma', 'negative'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_004',
      trigger: '/no_infarct',
      expansion: 'No acute infarction or areas of restricted diffusion are identified.',
      name: 'No Infarction',
      category: 'FINDING',
      subcategory: 'Brain',
      keywords: ['infarction', 'stroke', 'ischemia', 'dwi', 'negative'],
      variables: [],
      modalityTags: ['CT', 'MRI'],
      anatomyTags: ['HEAD', 'BRAIN'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_005',
      trigger: '/clear_lungs',
      expansion: 'Lungs are clear bilaterally. No focal consolidation, nodules, or masses.',
      name: 'Clear Lungs',
      category: 'FINDING',
      subcategory: 'Chest',
      keywords: ['clear', 'lungs', 'normal', 'no nodules'],
      variables: [],
      modalityTags: ['CT', 'X-RAY'],
      anatomyTags: ['CHEST', 'LUNGS'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: true,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_006',
      trigger: '/no_effusion',
      expansion: 'No pleural effusions or pneumothoraces are identified.',
      name: 'No Pleural Effusion',
      category: 'FINDING',
      subcategory: 'Chest',
      keywords: ['pleural effusion', 'pneumothorax', 'no fluid', 'negative'],
      variables: [],
      modalityTags: ['CT', 'X-RAY'],
      anatomyTags: ['CHEST', 'PLEURA'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_find_007',
      trigger: '/no_lympnad',
      expansion: 'No lymphadenopathy is identified in the mediastinum or hila.',
      name: 'No Lymphadenopathy',
      category: 'FINDING',
      subcategory: 'Chest',
      keywords: ['lymphadenopathy', 'lymph nodes', 'mediastinum', 'negative'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY'],
      anatomyTags: ['CHEST', 'MEDIASTINUM', 'HILA'],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ IMPRESSION SNIPPETS ============
    {
      id: 'snip_imp_001',
      trigger: '/impression_normal',
      expansion: '1. Normal examination.\n2. No acute abnormality identified.',
      name: 'Normal Impression',
      category: 'IMPRESSION',
      subcategory: 'Normal',
      keywords: ['normal', 'impression', 'negative', 'no abnormality'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: ['NORMAL'],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: true,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_imp_002',
      trigger: '/impression_equivocal',
      expansion: '1. Findings are equivocal. Clinical correlation is recommended.\n2. Consider follow-up imaging if clinically indicated.',
      name: 'Equivocal Impression',
      category: 'IMPRESSION',
      subcategory: 'Indeterminate',
      keywords: ['equivocal', 'uncertain', 'follow-up', 'correlation'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: ['INDETERMINATE'],
      urgency: 'URGENT',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ PATHOLOGY SNIPPETS ============
    {
      id: 'snip_path_001',
      trigger: '/mass',
      expansion: 'A ___ mass is identified in the ___. It measures ___ cm. There is ___ mass effect.',
      name: 'Mass Finding',
      category: 'PATHOLOGY',
      subcategory: 'Mass',
      keywords: ['mass', 'lesion', 'nodule', 'tumor'],
      variables: ['size', 'location', 'dimensions', 'mass effect'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: ['MASS'],
      urgency: 'URGENT',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_path_002',
      trigger: '/nodule',
      expansion: 'A ___ density nodule is identified in the ___. It measures ___ cm in greatest dimension.',
      name: 'Nodule Finding',
      category: 'PATHOLOGY',
      subcategory: 'Nodule',
      keywords: ['nodule', 'density', 'pulmonary', 'solitary'],
      variables: ['density type', 'location', 'size'],
      modalityTags: ['CT', 'X-RAY'],
      anatomyTags: ['LUNG'],
      pathologyTags: ['NODULE'],
      urgency: 'ELEVATED',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_path_003',
      trigger: '/consolidation',
      expansion: '___ consolidation is present in the ___. This may represent ___ .',
      name: 'Consolidation Finding',
      category: 'PATHOLOGY',
      subcategory: 'Consolidation',
      keywords: ['consolidation', 'pneumonia', 'atelectasis', 'opacification'],
      variables: ['type', 'location', 'etiology'],
      modalityTags: ['CT', 'X-RAY'],
      anatomyTags: ['LUNG'],
      pathologyTags: ['CONSOLIDATION'],
      urgency: 'URGENT',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ MEASUREMENT SNIPPETS ============
    {
      id: 'snip_meas_001',
      trigger: '/measure',
      expansion: 'The ___ measures ___ cm in greatest dimension.',
      name: 'Basic Measurement',
      category: 'MEASUREMENT',
      subcategory: 'Size',
      keywords: ['measure', 'size', 'dimension', 'cm'],
      variables: ['structure', 'dimension'],
      modalityTags: ['CT', 'MRI', 'ULTRASOUND', 'X-RAY'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_meas_002',
      trigger: '/hu',
      expansion: 'The lesion measures ___ Hounsfield units on non-contrast CT.',
      name: 'Hounsfield Units',
      category: 'MEASUREMENT',
      subcategory: 'Density',
      keywords: ['hu', 'hounsfield', 'density', 'attenuation'],
      variables: ['hu value'],
      modalityTags: ['CT'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ MODIFIER SNIPPETS ============
    {
      id: 'snip_mod_001',
      trigger: '/mild',
      expansion: 'Mild ___ is noted.',
      name: 'Mild Modifier',
      category: 'MODIFIER',
      subcategory: 'Severity',
      keywords: ['mild', 'slight', 'minimal', 'minor'],
      variables: ['finding'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_mod_002',
      trigger: '/moderate',
      expansion: 'Moderate ___ is noted.',
      name: 'Moderate Modifier',
      category: 'MODIFIER',
      subcategory: 'Severity',
      keywords: ['moderate', 'moderate degree'],
      variables: ['finding'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ELEVATED',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_mod_003',
      trigger: '/severe',
      expansion: 'Severe ___ is noted.',
      name: 'Severe Modifier',
      category: 'MODIFIER',
      subcategory: 'Severity',
      keywords: ['severe', 'marked', 'significant'],
      variables: ['finding'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'URGENT',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ COMPARISON SNIPPETS ============
    {
      id: 'snip_comp_001',
      trigger: '/compare',
      expansion: 'Compared to the prior study from ___, there is ___.',
      name: 'Comparison Phrase',
      category: 'COMPARISON',
      subcategory: 'Change',
      keywords: ['compared', 'prior', 'previous', 'change'],
      variables: ['date', 'change description'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_comp_002',
      trigger: '/stable',
      expansion: 'The finding is stable compared to the prior study.',
      name: 'Stable Finding',
      category: 'COMPARISON',
      subcategory: 'Stable',
      keywords: ['stable', 'unchanged', 'no change'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_comp_003',
      trigger: '/increased',
      expansion: 'The finding has increased in size since the prior study, now measuring ___ cm compared to ___ cm previously.',
      name: 'Increased Size',
      category: 'COMPARISON',
      subcategory: 'Progression',
      keywords: ['increased', 'enlarged', 'grown', 'progressed'],
      variables: ['current size', 'previous size'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ELEVATED',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_comp_004',
      trigger: '/decreased',
      expansion: 'The finding has decreased in size since the prior study, now measuring ___ cm compared to ___ cm previously.',
      name: 'Decreased Size',
      category: 'COMPARISON',
      subcategory: 'Improvement',
      keywords: ['decreased', 'reduced', 'smaller', 'improved'],
      variables: ['current size', 'previous size'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ FOLLOWUP SNIPPETS ============
    {
      id: 'snip_follow_001',
      trigger: '/fu_3mo',
      expansion: 'Follow-up imaging in 3 months is recommended to assess for interval change.',
      name: 'Follow-up 3 Months',
      category: 'FOLLOWUP',
      subcategory: 'Timing',
      keywords: ['follow-up', '3 months', 'interval', 'repeat'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_follow_002',
      trigger: '/fu_6mo',
      expansion: 'Follow-up imaging in 6 months is recommended to assess for interval change.',
      name: 'Follow-up 6 Months',
      category: 'FOLLOWUP',
      subcategory: 'Timing',
      keywords: ['follow-up', '6 months', 'interval', 'repeat'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_follow_003',
      trigger: '/fu_1yr',
      expansion: 'Annual follow-up imaging is recommended.',
      name: 'Follow-up 1 Year',
      category: 'FOLLOWUP',
      subcategory: 'Timing',
      keywords: ['follow-up', 'annual', 'yearly', 'year'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ ADDENDUM SNIPPETS ============
    {
      id: 'snip_add_001',
      trigger: '/addendum',
      expansion: 'ADDENDUM: This is an addendum to the original report dated ___.',
      name: 'Addendum Header',
      category: 'ADDENDUM',
      subcategory: 'Header',
      keywords: ['addendum', 'amendment', 'correction'],
      variables: ['original date'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    // ============ QUALITY SNIPPETS ============
    {
      id: 'snip_qual_001',
      trigger: '/limited',
      expansion: 'Examination is limited due to ___. Findings should be interpreted with caution.',
      name: 'Limited Quality',
      category: 'QUALITY',
      subcategory: 'Limitation',
      keywords: ['limited', 'suboptimal', 'artifact', 'motion'],
      variables: ['limitation'],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    },
    {
      id: 'snip_qual_002',
      trigger: '/adequate',
      expansion: 'Examination is of adequate technical quality for interpretation.',
      name: 'Adequate Quality',
      category: 'QUALITY',
      subcategory: 'Technical',
      keywords: ['adequate', 'quality', 'satisfactory'],
      variables: [],
      modalityTags: ['CT', 'MRI', 'X-RAY', 'ULTRASOUND'],
      anatomyTags: [],
      pathologyTags: [],
      urgency: 'ROUTINE',
      ageGroup: 'ADULT',
      usageCount: 0,
      isFavorite: false,
      isDefault: true,
      createdAt: '2024-01-01T00:00:00Z',
      updatedAt: '2024-01-01T00:00:00Z'
    }
  ];
}

// Generate additional snippets programmatically
function generateAdditionalSnippets() {
  const snippets = getSnippetData();
  
  const categories = SNIPPET_CATEGORIES;
  const bodyParts = [
    'HEAD', 'BRAIN', 'CEREBELLUM', 'BRAINSTEM', 'ORBIT', 'TEMPORAL BONE', 'NECK', 'THYROID', 'LARYNX',
    'CHEST', 'LUNG', 'MEDIASTINUM', 'HEART', 'AORTA', 'PLEURA',
    'ABDOMEN', 'LIVER', 'GALLBLADDER', 'PANCREAS', 'SPLEEN', 'KIDNEY', 'ADRENAL', 'AORTA', 'BOWEL',
    'PELVIS', 'BLADDER', 'PROSTATE', 'UTERUS', 'OVARY', 'TESTIS',
    'SPINE', 'CERVICAL SPINE', 'THORACIC SPINE', 'LUMBAR SPINE', 'CORD',
    'ARM', 'SHOULDER', 'ELBOW', 'WRIST', 'HAND',
    'LEG', 'HIP', 'KNEE', 'ANKLE', 'FOOT',
    'JOINT', 'BONE', 'MUSCLE', 'TENDON', 'LIGAMENT'
  ];
  const modalities = ['CT', 'MRI', 'X-RAY', 'ULTRASOUND', 'MAMMOGRAPHY', 'CTA', 'MRA', 'PET-CT'];
  const severities = ['MILD', 'MILD-MODERATE', 'MODERATE', 'MODERATE-SEVERE', 'SEVERE'];
  const locations = ['RIGHT', 'LEFT', 'BILATERAL', 'UPPER', 'LOWER', 'ANTERIOR', 'POSTERIOR', 'SUPERIOR', 'INFERIOR', 'MEDIAL', 'LATERAL', 'CENTRAL', 'PERIPHERAL'];
  
  let id = 100;
  
  // Generate anatomy snippets
  for (const bodyPart of bodyParts) {
    for (const category of categories.slice(0, 8)) {
      snippets.push({
        id: `snip_${category.toLowerCase()}_${bodyPart.toLowerCase().replace(' ', '_')}_${id}`,
        trigger: `/${bodyPart.toLowerCase().replace(' ', '_')}_${category.toLowerCase().substring(0, 4)}`,
        expansion: `${category} finding for ${bodyPart}.`,
        name: `${bodyPart} ${category}`,
        category,
        subcategory: bodyPart,
        keywords: [bodyPart.toLowerCase(), category.toLowerCase()],
        variables: [],
        modalityTags: modalities,
        anatomyTags: [bodyPart],
        pathologyTags: [],
        urgency: 'ROUTINE',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  // Generate pathology snippets
  const pathologies = ['MASS', 'CYST', 'NODULE', 'CALCIFICATION', 'ULCER', 'STENOSIS', 'DILATATION', 'HEMORRHAGE', 'EDEMA', 'NECROSIS', 'THROMBUS', 'EMBOLISM', 'FRACTURE', 'DISLOCATION', 'TEAR', 'RUPTURE', 'INFECTION', 'INFLAMMATION', 'TUMOR', 'METASTASIS'];
  for (const pathology of pathologies) {
    for (const bodyPart of bodyParts) {
      snippets.push({
        id: `snip_path_${pathology.toLowerCase()}_${id}`,
        trigger: `/${pathology.toLowerCase()}_${bodyPart.toLowerCase().replace(' ', '_').substring(0, 4)}`,
        expansion: `${pathology} identified in ${bodyPart}.`,
        name: `${pathology} ${bodyPart}`,
        category: 'PATHOLOGY',
        subcategory: pathology,
        keywords: [pathology.toLowerCase(), bodyPart.toLowerCase()],
        variables: ['size', 'location'],
        modalityTags: modalities,
        anatomyTags: [bodyPart],
        pathologyTags: [pathology],
        urgency: 'ELEVATED',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  // Generate severity modifier snippets
  for (const severity of severities) {
    for (const bodyPart of bodyParts) {
      snippets.push({
        id: `snip_mod_${severity.toLowerCase().replace('-', '_')}_${id}`,
        trigger: `/${severity.toLowerCase().replace('-', '_')}_${bodyPart.toLowerCase().replace(' ', '_').substring(0, 4)}`,
        expansion: `${severity} abnormality in ${bodyPart}.`,
        name: `${severity} ${bodyPart}`,
        category: 'MODIFIER',
        subcategory: severity,
        keywords: [severity.toLowerCase(), bodyPart.toLowerCase()],
        variables: [],
        modalityTags: modalities,
        anatomyTags: [bodyPart],
        pathologyTags: [],
        urgency: severity === 'SEVERE' || severity === 'MODERATE-SEVERE' ? 'URGENT' : 'ROUTINE',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  // Generate location-based snippets
  for (const location of locations) {
    for (const bodyPart of bodyParts) {
      snippets.push({
        id: `snip_loc_${location.toLowerCase()}_${id}`,
        trigger: `/${location.toLowerCase()}_${bodyPart.toLowerCase().replace(' ', '_').substring(0, 4)}`,
        expansion: `${location} ${bodyPart} appears normal.`,
        name: `${location} ${bodyPart}`,
        category: 'ANATOMY',
        subcategory: 'Location',
        keywords: [location.toLowerCase(), bodyPart.toLowerCase()],
        variables: [],
        modalityTags: modalities,
        anatomyTags: [bodyPart, location],
        pathologyTags: ['NORMAL'],
        urgency: 'ROUTINE',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  // Generate technique snippets
  const techniques = ['axial', 'coronal', 'sagittal', '3D', 'reconstruction', 'thin section', 'high resolution', 'multiplanar', 'contrast enhanced', 'double contrast', 'single phase', 'multi phase', 'arterial', 'venous', 'delayed'];
  for (const technique of techniques) {
    for (const modality of modalities) {
      snippets.push({
        id: `snip_tech_${technique.toLowerCase().replace(' ', '_')}_${id}`,
        trigger: `/${technique.toLowerCase().replace(' ', '_').substring(0, 6)}_${modality.toLowerCase()}`,
        expansion: `${technique} ${modality} images were obtained.`,
        name: `${technique} ${modality}`,
        category: 'TECHNIQUE',
        subcategory: technique,
        keywords: [technique.toLowerCase(), modality.toLowerCase()],
        variables: [],
        modalityTags: [modality],
        anatomyTags: [],
        pathologyTags: [],
        urgency: 'ROUTINE',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  // Generate follow-up timing snippets
  const followupTimings = ['1 WEEK', '2 WEEKS', '3 WEEKS', '1 MONTH', '6 WEEKS', '2 MONTHS', '3 MONTHS', '4 MONTHS', '6 MONTHS', '9 MONTHS', '1 YEAR', '18 MONTHS', '2 YEARS', '3 YEARS', '5 YEARS'];
  for (const timing of followupTimings) {
    for (const modality of modalities) {
      snippets.push({
        id: `snip_fu_${timing.toLowerCase().replace(' ', '_')}_${id}`,
        trigger: `/${timing.toLowerCase().replace(' ', '')}`,
        expansion: `Follow-up ${timing.toLowerCase()} with ${modality} is recommended.`,
        name: `Follow-up ${timing}`,
        category: 'FOLLOWUP',
        subcategory: 'Timing',
        keywords: ['follow-up', timing.toLowerCase()],
        variables: [],
        modalityTags: [modality],
        anatomyTags: [],
        pathologyTags: [],
        urgency: 'ROUTINE',
        ageGroup: 'ADULT',
        usageCount: 0,
        isFavorite: false,
        isDefault: false,
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z'
      });
      id++;
    }
  }
  
  return snippets;
}

export const snippetData = generateAdditionalSnippets();

export default {
  getSnippetData,
  snippetData,
  SNIPPET_CATEGORIES
};